/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as InvoiceRouteImport } from './routes/invoice'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyRoomsRouteImport } from './routes/my-rooms'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAllocationRouteImport } from './routes/admin/allocation'
import { Route as AdminBuildingsRouteImport } from './routes/admin/buildings'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminInvoiceRouteImport } from './routes/admin/invoice'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminReportRouteImport } from './routes/admin/report'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminRevenueRouteImport } from './routes/admin/revenue'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as StaffAllocationRouteImport } from './routes/staff/allocation'
import { Route as StaffBookingsRouteImport } from './routes/staff/bookings'
import { Route as StaffBuildingsRouteImport } from './routes/staff/buildings'
import { Route as StaffCustomersRouteImport } from './routes/staff/customers'
import { Route as StaffDashboardRouteImport } from './routes/staff/dashboard'
import { Route as StaffFinanceRouteImport } from './routes/staff/finance'
import { Route as StaffInvoiceRouteImport } from './routes/staff/invoice'
import { Route as StaffLoginRouteImport } from './routes/staff/login'
import { Route as StaffReportsRouteImport } from './routes/staff/reports'
import { Route as StaffRevenueRouteImport } from './routes/staff/revenue'
import { Route as StaffRoomsRouteImport } from './routes/staff/rooms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceRoute = InvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRoomsRoute = MyRoomsRouteImport.update({
  id: '/my-rooms',
  path: '/my-rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAllocationRoute = AdminAllocationRouteImport.update({
  id: '/allocation',
  path: '/allocation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBuildingsRoute = AdminBuildingsRouteImport.update({
  id: '/buildings',
  path: '/buildings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoiceRoute = AdminInvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportRoute = AdminReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffAllocationRoute = StaffAllocationRouteImport.update({
  id: '/allocation',
  path: '/allocation',
  getParentRoute: () => StaffRoute,
} as any)
const StaffBookingsRoute = StaffBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => StaffRoute,
} as any)
const StaffBuildingsRoute = StaffBuildingsRouteImport.update({
  id: '/buildings',
  path: '/buildings',
  getParentRoute: () => StaffRoute,
} as any)
const StaffCustomersRoute = StaffCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => StaffRoute,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StaffRoute,
} as any)
const StaffFinanceRoute = StaffFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => StaffRoute,
} as any)
const StaffInvoiceRoute = StaffInvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => StaffRoute,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => StaffRoute,
} as any)
const StaffReportsRoute = StaffReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => StaffRoute,
} as any)
const StaffRevenueRoute = StaffRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => StaffRoute,
} as any)
const StaffRoomsRoute = StaffRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => StaffRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/invoice': typeof InvoiceRoute
  '/login': typeof LoginRoute
  '/my-rooms': typeof MyRoomsRoute
  '/staff': typeof StaffRouteWithChildren
  '/admin/allocation': typeof AdminAllocationRoute
  '/admin/buildings': typeof AdminBuildingsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/invoice': typeof AdminInvoiceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/report': typeof AdminReportRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/staff/allocation': typeof StaffAllocationRoute
  '/staff/bookings': typeof StaffBookingsRoute
  '/staff/buildings': typeof StaffBuildingsRoute
  '/staff/customers': typeof StaffCustomersRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/finance': typeof StaffFinanceRoute
  '/staff/invoice': typeof StaffInvoiceRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/reports': typeof StaffReportsRoute
  '/staff/revenue': typeof StaffRevenueRoute
  '/staff/rooms': typeof StaffRoomsRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invoice': typeof InvoiceRoute
  '/login': typeof LoginRoute
  '/my-rooms': typeof MyRoomsRoute
  '/admin/allocation': typeof AdminAllocationRoute
  '/admin/buildings': typeof AdminBuildingsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/invoice': typeof AdminInvoiceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/report': typeof AdminReportRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/staff/allocation': typeof StaffAllocationRoute
  '/staff/bookings': typeof StaffBookingsRoute
  '/staff/buildings': typeof StaffBuildingsRoute
  '/staff/customers': typeof StaffCustomersRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/finance': typeof StaffFinanceRoute
  '/staff/invoice': typeof StaffInvoiceRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/reports': typeof StaffReportsRoute
  '/staff/revenue': typeof StaffRevenueRoute
  '/staff/rooms': typeof StaffRoomsRoute
  '/admin': typeof AdminIndexRoute
  '/staff': typeof StaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/invoice': typeof InvoiceRoute
  '/login': typeof LoginRoute
  '/my-rooms': typeof MyRoomsRoute
  '/staff': typeof StaffRouteWithChildren
  '/admin/allocation': typeof AdminAllocationRoute
  '/admin/buildings': typeof AdminBuildingsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/invoice': typeof AdminInvoiceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/report': typeof AdminReportRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/staff/allocation': typeof StaffAllocationRoute
  '/staff/bookings': typeof StaffBookingsRoute
  '/staff/buildings': typeof StaffBuildingsRoute
  '/staff/customers': typeof StaffCustomersRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/finance': typeof StaffFinanceRoute
  '/staff/invoice': typeof StaffInvoiceRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/reports': typeof StaffReportsRoute
  '/staff/revenue': typeof StaffRevenueRoute
  '/staff/rooms': typeof StaffRoomsRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/invoice'
    | '/login'
    | '/my-rooms'
    | '/staff'
    | '/admin/allocation'
    | '/admin/buildings'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/invoice'
    | '/admin/login'
    | '/admin/report'
    | '/admin/reports'
    | '/admin/revenue'
    | '/staff/allocation'
    | '/staff/bookings'
    | '/staff/buildings'
    | '/staff/customers'
    | '/staff/dashboard'
    | '/staff/finance'
    | '/staff/invoice'
    | '/staff/login'
    | '/staff/reports'
    | '/staff/revenue'
    | '/staff/rooms'
    | '/admin/'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invoice'
    | '/login'
    | '/my-rooms'
    | '/admin/allocation'
    | '/admin/buildings'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/invoice'
    | '/admin/login'
    | '/admin/report'
    | '/admin/reports'
    | '/admin/revenue'
    | '/staff/allocation'
    | '/staff/bookings'
    | '/staff/buildings'
    | '/staff/customers'
    | '/staff/dashboard'
    | '/staff/finance'
    | '/staff/invoice'
    | '/staff/login'
    | '/staff/reports'
    | '/staff/revenue'
    | '/staff/rooms'
    | '/admin'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/invoice'
    | '/login'
    | '/my-rooms'
    | '/staff'
    | '/admin/allocation'
    | '/admin/buildings'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/invoice'
    | '/admin/login'
    | '/admin/report'
    | '/admin/reports'
    | '/admin/revenue'
    | '/staff/allocation'
    | '/staff/bookings'
    | '/staff/buildings'
    | '/staff/customers'
    | '/staff/dashboard'
    | '/staff/finance'
    | '/staff/invoice'
    | '/staff/login'
    | '/staff/reports'
    | '/staff/revenue'
    | '/staff/rooms'
    | '/admin/'
    | '/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  InvoiceRoute: typeof InvoiceRoute
  LoginRoute: typeof LoginRoute
  MyRoomsRoute: typeof MyRoomsRoute
  StaffRoute: typeof StaffRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice': {
      id: '/invoice'
      path: '/invoice'
      fullPath: '/invoice'
      preLoaderRoute: typeof InvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-rooms': {
      id: '/my-rooms'
      path: '/my-rooms'
      fullPath: '/my-rooms'
      preLoaderRoute: typeof MyRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/allocation': {
      id: '/admin/allocation'
      path: '/allocation'
      fullPath: '/admin/allocation'
      preLoaderRoute: typeof AdminAllocationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/buildings': {
      id: '/admin/buildings'
      path: '/buildings'
      fullPath: '/admin/buildings'
      preLoaderRoute: typeof AdminBuildingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoice': {
      id: '/admin/invoice'
      path: '/invoice'
      fullPath: '/admin/invoice'
      preLoaderRoute: typeof AdminInvoiceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/report': {
      id: '/admin/report'
      path: '/report'
      fullPath: '/admin/report'
      preLoaderRoute: typeof AdminReportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/allocation': {
      id: '/staff/allocation'
      path: '/allocation'
      fullPath: '/staff/allocation'
      preLoaderRoute: typeof StaffAllocationRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/bookings': {
      id: '/staff/bookings'
      path: '/bookings'
      fullPath: '/staff/bookings'
      preLoaderRoute: typeof StaffBookingsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/buildings': {
      id: '/staff/buildings'
      path: '/buildings'
      fullPath: '/staff/buildings'
      preLoaderRoute: typeof StaffBuildingsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/customers': {
      id: '/staff/customers'
      path: '/customers'
      fullPath: '/staff/customers'
      preLoaderRoute: typeof StaffCustomersRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/dashboard': {
      id: '/staff/dashboard'
      path: '/dashboard'
      fullPath: '/staff/dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/finance': {
      id: '/staff/finance'
      path: '/finance'
      fullPath: '/staff/finance'
      preLoaderRoute: typeof StaffFinanceRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/invoice': {
      id: '/staff/invoice'
      path: '/invoice'
      fullPath: '/staff/invoice'
      preLoaderRoute: typeof StaffInvoiceRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/reports': {
      id: '/staff/reports'
      path: '/reports'
      fullPath: '/staff/reports'
      preLoaderRoute: typeof StaffReportsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/revenue': {
      id: '/staff/revenue'
      path: '/revenue'
      fullPath: '/staff/revenue'
      preLoaderRoute: typeof StaffRevenueRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/rooms': {
      id: '/staff/rooms'
      path: '/rooms'
      fullPath: '/staff/rooms'
      preLoaderRoute: typeof StaffRoomsRouteImport
      parentRoute: typeof StaffRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAllocationRoute: typeof AdminAllocationRoute
  AdminBuildingsRoute: typeof AdminBuildingsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminInvoiceRoute: typeof AdminInvoiceRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminReportRoute: typeof AdminReportRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAllocationRoute: AdminAllocationRoute,
  AdminBuildingsRoute: AdminBuildingsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminInvoiceRoute: AdminInvoiceRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminReportRoute: AdminReportRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StaffRouteChildren {
  StaffAllocationRoute: typeof StaffAllocationRoute
  StaffBookingsRoute: typeof StaffBookingsRoute
  StaffBuildingsRoute: typeof StaffBuildingsRoute
  StaffCustomersRoute: typeof StaffCustomersRoute
  StaffDashboardRoute: typeof StaffDashboardRoute
  StaffFinanceRoute: typeof StaffFinanceRoute
  StaffInvoiceRoute: typeof StaffInvoiceRoute
  StaffLoginRoute: typeof StaffLoginRoute
  StaffReportsRoute: typeof StaffReportsRoute
  StaffRevenueRoute: typeof StaffRevenueRoute
  StaffRoomsRoute: typeof StaffRoomsRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffAllocationRoute: StaffAllocationRoute,
  StaffBookingsRoute: StaffBookingsRoute,
  StaffBuildingsRoute: StaffBuildingsRoute,
  StaffCustomersRoute: StaffCustomersRoute,
  StaffDashboardRoute: StaffDashboardRoute,
  StaffFinanceRoute: StaffFinanceRoute,
  StaffInvoiceRoute: StaffInvoiceRoute,
  StaffLoginRoute: StaffLoginRoute,
  StaffReportsRoute: StaffReportsRoute,
  StaffRevenueRoute: StaffRevenueRoute,
  StaffRoomsRoute: StaffRoomsRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  InvoiceRoute: InvoiceRoute,
  LoginRoute: LoginRoute,
  MyRoomsRoute: MyRoomsRoute,
  StaffRoute: StaffRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
